services:
  pg-db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: UBLIm3C15c0kDWh4tg0t
      POSTGRES_USER: ffpg_back
      POSTGRES_DB: pg-findfripes

# docker compose -f postgres.yaml up -d